Repository Pho3niX90/solis_modbus, pull requests merged in 2025-04, with the labels that each got.

#183 Enhancement: Add startup poll mode, new inverter models, & sensor adjustments
  custom_components/solis_modbus/data/enums.py
  custom_components/solis_modbus/data/solis_config.py
  custom_components/solis_modbus/data_retrieval.py
  custom_components/solis_modbus/manifest.json
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensor_data/string_sensors.py
  custom_components/solis_modbus/sensors/solis_base_sensor.py
Labels: Review effort 3/5, - Enhancement

#185 Add STARTUP Polling, New Inverter Models, and Sensor Enhancements
  custom_components/solis_modbus/data_retrieval.py
  custom_components/solis_modbus/manifest.json
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensors/solis_derived_sensor.py
Labels: Review effort 3/5, - Bug fix - Enhancement

#192 Add BMS support and reset offline grid power
  custom_components/solis_modbus/data/enums.py
  custom_components/solis_modbus/data/solis_config.py
  custom_components/solis_modbus/manifest.json
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensors/solis_sensor.py
Labels: Enhancement, Bug fix, Review effort 3/5

#197 Fix unique ID for Load Total Consumption Energy sensor
  custom_components/solis_modbus/sensor_data/string_sensors.py
Labels: Bug fix, Review effort 1/5

#196 Add sensor watchdog for availability timeout
  custom_components/solis_modbus/sensors/solis_sensor.py
Labels: Enhancement, Bug fix, Review effort 3/5

#199 Add TCP feature support and S6-EH3P10K-H-ZP inverter
  custom_components/solis_modbus/data/enums.py
  custom_components/solis_modbus/data/solis_config.py
  custom_components/solis_modbus/sensors/solis_base_sensor.py
  custom_components/solis_modbus/sensors/solis_sensor.py
Labels: Enhancement, Review effort 2/5

#203 Introduce poll_speed and refine sensor behavior
  README.md
  custom_components/solis_modbus/manifest.json
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensors/solis_base_sensor.py
  custom_components/solis_modbus/sensors/solis_sensor.py
Labels: Enhancement, Bug fix, Review effort 3/5
