Repository Pho3niX90/solis_modbus, pull requests merged in 2025-06, with the labels that each got.

#239 Support write_register and dynamic inverter settings
  custom_components/solis_modbus/__init__.py
  custom_components/solis_modbus/data/enums.py
  custom_components/solis_modbus/data/solis_config.py
  custom_components/solis_modbus/data_retrieval.py
  custom_components/solis_modbus/helpers.py
  custom_components/solis_modbus/modbus_controller.py
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensor_data/string_sensors.py
  custom_components/solis_modbus/sensors/solis_base_sensor.py
  custom_components/solis_modbus/sensors/solis_number_sensor.py
  custom_components/solis_modbus/switch.py
  custom_components/solis_modbus/time.py
  custom_components/solis_modbus/translations/en.json
Labels: Enhancement, Review effort 3/5

#240 Add inverter identification to device identifiers
  custom_components/solis_modbus/const.py
  custom_components/solis_modbus/data_retrieval.py
  custom_components/solis_modbus/helpers.py
  custom_components/solis_modbus/modbus_controller.py
  custom_components/solis_modbus/sensors/solis_binary_sensor.py
  custom_components/solis_modbus/sensors/solis_derived_sensor.py
  custom_components/solis_modbus/sensors/solis_number_sensor.py
  custom_components/solis_modbus/sensors/solis_select_entity.py
  custom_components/solis_modbus/sensors/solis_sensor.py
  custom_components/solis_modbus/time.py
Labels: Bug fix, Review effort 2/5

#241 Add support for Solis 1P(2.5-6)K-4G inverter model
  README.md
  custom_components/solis_modbus/data/solis_config.py
Labels: Enhancement, Review effort 2/5

#247 Increase max charge/discharge current step resolution
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
Labels: Enhancement, Review effort 1/5
