Repository Pho3niX90/solis_modbus, pull requests merged in 2025-05, with the labels that each got.

#204 Support multi-inverter identification and HV/LV battery models
  .github/workflows/test-sensor-definitions.yaml
  README.md
  custom_components/solis_modbus/__init__.py
  custom_components/solis_modbus/config_flow.py
  custom_components/solis_modbus/data/enums.py
  custom_components/solis_modbus/data/solis_config.py
  custom_components/solis_modbus/data_retrieval.py
  custom_components/solis_modbus/manifest.json
  custom_components/solis_modbus/modbus_controller.py
  custom_components/solis_modbus/select.py
  custom_components/solis_modbus/sensor_data/hybrid_sensors.py
  custom_components/solis_modbus/sensors/solis_base_sensor.py
  custom_components/solis_modbus/sensors/solis_binary_sensor.py
  custom_components/solis_modbus/sensors/solis_number_sensor.py
  custom_components/solis_modbus/sensors/solis_select_entity.py
  custom_components/solis_modbus/switch.py
  custom_components/solis_modbus/translations/af.json
  custom_components/solis_modbus/translations/de.json
  custom_components/solis_modbus/translations/en.json
  custom_components/solis_modbus/translations/es.json
  custom_components/solis_modbus/translations/fr.json
  custom_components/solis_modbus/translations/pt.json
  images/img.png
  images/img_1.png
  images/img_2.png
  images/img_3.png
  images/img_4.png
  images/img_jk_bms.png
  images/img_solar_card.png
  tests/test_sensor_definitions.py
Labels: documentation, Enhancement, Bug fix, Review effort 4/5, Tests

#209 Add multi-inverter identification and CI release enhancements
  .github/workflows/release.yaml
  custom_components/solis_modbus/modbus_controller.py
  custom_components/solis_modbus/sensors/solis_binary_sensor.py
  custom_components/solis_modbus/sensors/solis_derived_sensor.py
  custom_components/solis_modbus/sensors/solis_number_sensor.py
  custom_components/solis_modbus/sensors/solis_select_entity.py
  custom_components/solis_modbus/sensors/solis_sensor.py
  custom_components/solis_modbus/time.py
Labels: Enhancement, Review effort 3/5

#213 Enhance S6-EH3P10K-H-ZP support and power settings
  custom_components/solis_modbus/sensors/solis_base_sensor.py
Labels: Enhancement, Review effort 3/5

#219 Align switch & select work_mode logic and names
  custom_components/solis_modbus/switch.py
Labels: Enhancement, Bug fix, Review effort 3/5

#220 Add inverter-type conditional selects and power limit switch
  custom_components/solis_modbus/select.py
  custom_components/solis_modbus/sensor_data/string_sensors.py
  custom_components/solis_modbus/sensors/solis_binary_sensor.py
  custom_components/solis_modbus/switch.py
Labels: Enhancement, Review effort 3/5

#226 Add slave ID support and power limit enhancements
  custom_components/solis_modbus/__init__.py
  custom_components/solis_modbus/config_flow.py
  custom_components/solis_modbus/helpers.py
  custom_components/solis_modbus/number.py
  custom_components/solis_modbus/select.py
  custom_components/solis_modbus/sensor.py
  custom_components/solis_modbus/sensor_data/string_sensors.py
  custom_components/solis_modbus/sensors/solis_binary_sensor.py
  custom_components/solis_modbus/switch.py
  custom_components/solis_modbus/time.py
  tests/test_select_definitions_from_code.py
  tests/test_switch_definitions_from_code.py
Labels: Enhancement, Bug fix, Review effort 3/5

#229 Fix model condition for S6-EH3P10K-H-ZP multiplier logic
  custom_components/solis_modbus/sensors/solis_base_sensor.py
Labels: Bug fix, Review effort 1/5
